<?php

return [
    'states' => [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "District Of Columbia",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming"
    ],

    'graduation_designation' => [
        "STEM Scholar",
        "IB Diploma Candidate",
        "Business Certification",
        "Conservatory Arts Certification",
        "Summa Cum Laude",
        "Magna Cum Laude",
        "Cum Laude",
        "Valedictorian",
        "Salutatorian",
    ],

    'cities' => [
        "New York",
        "Los Angeles",
        "Chicago",
        "Houston"
    ],

    'ib_courses' => [
        "Biology",
        "Business Management",
        "Chemistry",
        "Classical Languages",
        "Computer Science",
        "Dance",
        "Design Technology",
        "Economics",
        "Environmental Systems and Societies",
        "Film",
        "Geography",
        "Global Politics",
        "Information Technology in a Global Society",
        "Language A: Literature",
        "Language A: Language and Literature",
        "Language ab Initio",
        "Language B",
        "Literature and Performance",
        "Mathematics: Analysis and Approaches",
        "Mathematics: Applications and Interpretations",
        "Music",
        "Philosophy",
        "Psychology",
        "Physics",
        "Social and Cultural Anthropology",
        "Sports, Exercise, and Health Science",
        "Theatre",
        "Theory of Knowledge",
        "Visual Art",
        "World Religion"
    ],

    'ap_courses' => [
        "Art and Design - 2-D Design",
        "Art and Design - 3-D Design",
        "Art and Design - Drawing",
        "Art History",
        "Biology",
        "Calculus AB",
        "Calculus BC",
        "Chemistry",
        "Chinese Language and Culture",
        "Computer Science A",
        "Computer Science Principles",
        "English Language and Composition",
        "English Literature and Composition",
        "Environmental Science",
        "European History",
        "French Language and Culture",
        "German Language and Culture",
        "Government and Politics (Comparative)",
        "Government and Politics (US)",
        "Human Geography",
        "Italian Language and Culture",
        "Japanese Language and Culture",
        "Latin",
        "Macroeconomics",
        "Microeconomics",
        "Music Theory",
        "Physics 1: Algebra-Based",
        "Physics 2: Algebra-Based",
        "Physics C: Electricity and Magnetism",
        "Physics C: Mechanics",
        "Psychology",
        "Research",
        "Seminar",
        "Spanish Language and Culture",
        "Spanish Literature and Culture",
        "Statistics",
        "US History",
        "World History: Modern"
    ],

    'honors_courses_name' => [
        "Algebra I",
        "Algebra II",
        "Biology",
        "Chemistry",
        "Economics",
        "English 9",
        "English10",
        "English 11",
        "English 12",
        "Geometry",
        "Physics",
        "Physical Science",
        "Pre-Calculus",
        "U.S. History",
        "U.S. Geography",
        "World Geography",
        "World History",
        "American Sign Language",
        "Ancient Greek",
        "Arabic",
        "Chinese",
        "French",
        "German",
        "Hebrew",
        "Italian",
        "Japanese",
        "Korean",
        "Latin",
        "Portuguese",
        "Russian",
        "Spanish",
    ],

    "demonstrated_positions" => [
        "Assistant",
        "Attendee",
        "Barista",
        "Busser",
        "Chair",
        "Captain",
        "Chef",
        "Co-Captain",
        "Co-Leader",
        "Co-Founder",
        "Conducted Career Interview",
        "Created",
        "Customer Service",
        "Employee",
        "Developer",
        "Director",
        "Front of House Team Member",
        "Founder",
        "Intern",
        "Internship",
        "Initiated",
        "Job Shadow",
        "JV Starter",
        "JV Member",
        "Lead",
        "Leader",
        "Manager",
        "Member",
        "Observed",
        "Officer",
        "Operated",
        "Organizer",
        "Owner",
        "Owner & Founder",
        "Participant",
        "President",
        "Recorder",
        "Reporter",
        "Representative",
        "Researcher",
        "Scout",
        "Secretary",
        "Self-Employed",
        "Shift Lead",
        "Shift Manager",
        "Starter",
        "State Officer",
        "State Representative",
        "Summer Student",
        "Student",
        "Vice President",
        "Team Manager",
        "Treasurer",
        "Varsity Starter",
        "Varsity Member",
        "Volunteer",
        "Worker",
    ],

    "status" => [
        "Appointed",
        "Assigned",
        "Awardee",
        "Awarded",
        "Created",
        "Developed",
        "Earned",
        "Elected",
        "Finalist",
        "Member",
        "Nominated",
        "Recipient",
        "Runner-Up",
        "Selected",
        "Semi-Finalist",
    ],

    "honor_achievement_awards" => [
        "1st Team All-State",
        "2nd Team All-State",
        "1st Team All-Conference",
        "2nd Team All-Conference",
        "Honorable Mention",
        "Academic Letter",
        "Black Belt, Taekwondo",
        "Commended Scholar",
        "Eagle Scout",
        "Honor Roll Recognition",
        "MVP",
        "National English Honor Society",
        "National Merit Finalist",
        "National Merit Semi-Finalist",
        "National Merit Awardee",
        "National Qualifier",
        "Order of the Arrow, BSA Honor Society",
        "Pending Salutatorian",
        "Pending Valedictorian",
        "Salutatorian",
        "Science National Honor Society",
        "Spanish National Honor Society",
        "State Qualifier",
        "Valedictorian",
        "Volunteer Letter",


    ],

    'leadership_organization' => [
        "Air Patrol",
        "Alliance Club",
        "Art Club",
        "Band",
        "Boy Scouts",
        "Computer Technology",
        "Choir",
        "Chamber Choir",
        "Chamber Orchestra",
        "Chess Team",
        "Concert Band",
        "DECA",
        "Debate Team",
        "Diversity Club",
        "Drama Club",
        "Eco Club",
        "Environmental Club",
        "FBLA",
        "FCA",
        "FFA",
        "4-H Club",
        "Foreign Exchange",
        "Gay-Straight Alliance",
        "Girl Scouts",
        "History Club",
        "Interact Club",
        "International Thespian Society",
        "Jazz Band",
        "Jazz Choir",
        "Journalism Club",
        "Junior ROTC",
        "Key Club",
        "Latin Club",
        "Math Club",
        "Math Olympiad",
        "Marching Band",
        "Mental Health Awareness Club",
        "Mock Trial",
        "Model UN",
        "National Honor Society",
        "National English Honor Society",
        "Newspaper",
        "Orchestra",
        "Pitt Band",
        "Phi Alpha Theta Honor Society",
        "Publications",
        "Robotics",
        "Science Olympiad",
        "Social Justice Club",
        "Social Media Team",
        "Spanish Club",
        "Student Alliance",
        "Student Council",
        "Student Government",
        "Student Radio/TV Club",
        "Speech Team",
        "Technical Theatre",
        "Theatre",
        "Yearbook Staff",

    ],

    "athletics_position" => [
        "Aerobatics",
        "Archery",
        "Baseball Team",
        "Basketball Team",
        "Bowling Team",
        "Cheer Team",
        "Chess Team",
        "Competitive Cheer & Dance Team",
        "Cross Country Team",
        "Cycling Team",
        "Dance Team",
        "Field Hockey Team",
        "Frisbee Golf Team",
        "Football Team",
        "Gymnastics Team",
        "Golf Team",
        "Hiking",
        "Ice Hockey Team",
        "Lacrosse Team",
        "Mascot",
        "Mountain Biking Team",
        "Rugby Team",
        "Rock Climbing",
        "Skiing",
        "Ski Team",
        "Swim Team",
        "Swim & Dive Team",
        "Soccer Team",
        "Tennis Team",
        "Track & Field Team",
        "Volleyball Team",
        "Water Polo Team",


    ],

    "intended_college_major" => [
        "Music Education",
        "Art, General",
        "Design & Visual Communications, General",
        "Integrated Corporate Communications",
        "Interior Design",
        "Theatre Arts/Drama",
        "Cinema/Film/Video Studies",
        "Fine & Studio Arts",
        "Music",
        "Graphic Design",
        "Photography",
        "Fine & Studio Arts",
        "Music",
        "Business Administration/Mgmt, General",
        "Accounting",
        "Business/Managerial Economics",
        "Finance",
        "Travel/Tourism Services Management",
        "International Business Management",
        "Management Quantitative Methods",
        "Marketing Management & Research",
        "Fashion Merchandising",
        "Business Administration/Mgmt, General",
        "Accounting Technician",
        "Management Quantitative Methods",
        "Agricultural Public Services",
        "Communications, General",
        "Mass Communications",
        "Journalism, Print",
        "Journalism, Broadcast",
        "Radio & Television Communications",
        "Public Relations & Organizational Comm",
        "Advertising",
        "Communications, General",
        "Journalism, Print",
        "Family & Consumer Sciences, General",
        "Food & Nutrition",
        "Child Development",
        "Parks, Recreation & Leisure Studies",
        "Health & Physical Education/Fitness",
        "Sport & Fitness Admin/Management",
        "Exercise Sci/Physiology/Kinesiology",
        "Corrections",
        "Criminal Justice",
        "Human Services, General",
        "Social Work",
        "Public Health",
        "Computer & Information Sci, General",
        "Information Science",
        "Mathematics, General",
        "Management Information Systems",
        "Computer Science",
        "Data Science",
        "Actuarial",
        "Architecture",
        "Landscape Architecture",
        "Engineering, General",
        "Aerospace/Astronautical Engineering",
        "Chemical Engineering",
        "Civil Engineering",
        "Computer Engineering",
        "Electrical, Electronics & Comm Eng",
        "Mechanical Engineering",
        "Industrial Engineering",
        "Quality Control & Safety Technologies",
        "Mechanical Eng Related Technology",
        "Construction/Building Technology",
        "Aviation & Airway Science",
        "Engineering, General",
        "Engineering Technology, General",
        "Automotive Engineering Technology",
        "Construction/Building Technology",
        "Architectural Drafting/CAD Technology",
        "Teacher Education, General",
        "Special Education",
        "Elementary Education",
        "Early Childhood Education",
        "Secondary Education",
        "English/Language Arts Educ",
        "Mathematics Education",
        "Physical Education & Coaching",
        "Social Studies/Sciences Education",
        "Nutrition Sciences",
        "Communication Disorders Services",
        "Dental Hygiene",
        "Medical Radiologic Technology",
        "Medicine (Pre-medicine)",
        "Nursing, Registered (BS/RN)",
        "Nursing (NP)",
        "Pharmacy (Pre-pharmacy)",
        "Physical Therapy (Pre-phys therapy)",
        "Occupational Therapy (Pre-Occupational therapy)",
        "Veterinary Medicine (Pre-veterinarian)",
        "Physical Therapy Assisting",
        "Veterinarian Technology/Assisting",
        "Respiratory Therapy Technology",
        "Medical Laboratory Technology",
        "Speech Pathology",
        "Optometry",
        "Area Studies, Other",
        "Foreign Languages/Literature, General",
        "Spanish Language & Literature",
        "English Language & Literature, General",
        "Rhetoric",
        "Liberal Arts & General Studies",
        "Philosophy",
        "Divinity/Ministry",
        "Religion",
        "Liberal Arts & General Studies",
        "Fire Protection & Safety Technology",
        "Construction Management",
        "Heating/Air Cond/Refrig Install/Repair",
        "Autobody/Collision Repair/Technology",
        "Diesel Mechanics/Technology",
        "Welding",
        "Electrician",
        "International & Global Studies",
        "Psychology, General",
        "Psychologist",
        "Psychiatrist",
        "Social Sciences, General",
        "Anthropology",
        "Criminology",
        "Economics",
        "Geography & Cartography",
        "Pre-Law",
        "Political Science & Government",
        "Sociology",
        "History",
        "Social Sciences, General",
        "Sociology"
    ],

    "intended_college_minor" => [
        "Music Education",
        "Art, General",
        "Design & Visual Communications, General",
        "Integrated Corporate Communications",
        "Interior Design",
        "Theatre Arts/Drama",
        "Cinema/Film/Video Studies",
        "Fine & Studio Arts",
        "Music",
        "Graphic Design",
        "Photography",
        "Fine & Studio Arts",
        "Music",
        "Business Administration/Mgmt, General",
        "Accounting",
        "Business/Managerial Economics",
        "Finance",
        "Travel/Tourism Services Management",
        "International Business Management",
        "Management Quantitative Methods",
        "Marketing Management & Research",
        "Fashion Merchandising",
        "Business Administration/Mgmt, General",
        "Accounting Technician",
        "Management Quantitative Methods",
        "Agricultural Public Services",
        "Communications, General",
        "Mass Communications",
        "Journalism, Print",
        "Journalism, Broadcast",
        "Radio & Television Communications",
        "Public Relations & Organizational Comm",
        "Advertising",
        "Communications, General",
        "Journalism, Print",
        "Family & Consumer Sciences, General",
        "Food & Nutrition",
        "Child Development",
        "Parks, Recreation & Leisure Studies",
        "Health & Physical Education/Fitness",
        "Sport & Fitness Admin/Management",
        "Exercise Sci/Physiology/Kinesiology",
        "Corrections",
        "Criminal Justice",
        "Human Services, General",
        "Social Work",
        "Public Health",
        "Computer & Information Sci, General",
        "Information Science",
        "Mathematics, General",
        "Management Information Systems",
        "Computer Science",
        "Data Science",
        "Actuarial",
        "Architecture",
        "Landscape Architecture",
        "Engineering, General",
        "Aerospace/Astronautical Engineering",
        "Chemical Engineering",
        "Civil Engineering",
        "Computer Engineering",
        "Electrical, Electronics & Comm Eng",
        "Mechanical Engineering",
        "Industrial Engineering",
        "Quality Control & Safety Technologies",
        "Mechanical Eng Related Technology",
        "Construction/Building Technology",
        "Aviation & Airway Science",
        "Engineering, General",
        "Engineering Technology, General",
        "Automotive Engineering Technology",
        "Construction/Building Technology",
        "Architectural Drafting/CAD Technology",
        "Teacher Education, General",
        "Special Education",
        "Elementary Education",
        "Early Childhood Education",
        "Secondary Education",
        "English/Language Arts Educ",
        "Mathematics Education",
        "Physical Education & Coaching",
        "Social Studies/Sciences Education",
        "Nutrition Sciences",
        "Communication Disorders Services",
        "Dental Hygiene",
        "Medical Radiologic Technology",
        "Medicine (Pre-medicine)",
        "Nursing, Registered (BS/RN)",
        "Nursing (NP)",
        "Pharmacy (Pre-pharmacy)",
        "Physical Therapy (Pre-phys therapy)",
        "Occupational Therapy (Pre-Occupational therapy)",
        "Veterinary Medicine (Pre-veterinarian)",
        "Physical Therapy Assisting",
        "Veterinarian Technology/Assisting",
        "Respiratory Therapy Technology",
        "Medical Laboratory Technology",
        "Speech Pathology",
        "Optometry",
        "Area Studies, Other",
        "Foreign Languages/Literature, General",
        "Spanish Language & Literature",
        "English Language & Literature, General",
        "Rhetoric",
        "Liberal Arts & General Studies",
        "Philosophy",
        "Divinity/Ministry",
        "Religion",
        "Liberal Arts & General Studies",
        "Fire Protection & Safety Technology",
        "Construction Management",
        "Heating/Air Cond/Refrig Install/Repair",
        "Autobody/Collision Repair/Technology",
        "Diesel Mechanics/Technology",
        "Welding",
        "Electrician",
        "International & Global Studies",
        "Psychology, General",
        "Psychologist",
        "Psychiatrist",
        "Social Sciences, General",
        "Anthropology",
        "Criminology",
        "Economics",
        "Geography & Cartography",
        "Pre-Law",
        "Political Science & Government",
        "Sociology",
        "History",
        "Social Sciences, General",
        "Sociology"
    ],

    "languages" => [
        "Ancient Greek",
        "Arabic",
        "Chinese",
        "French",
        "German",
        "Hebrew",
        "Italian",
        "Japanese",
        "Korean",
        "Latin",
        "Portuguese",
        "Russian",
        "Spanish"
    ],

    "reminders_frequency" => [
        "Daily",
        "Weekly",
        "Monthly",
    ],
    
    'types_of_application' => [
        'Common App',
        'Coalition App',
        'Universal App',
        'College System App',
        'Apply Directly',
    ],
    'admission_options' => [
        'Early Action',
        'Regular Decision',
        'Rolling Admission',
        'Early Decision',
        'Early Decision II',
    ],
    'college_list_status' => [
        'Applied',
        'Not Applied',
        'Not Applicable',
    ],
    'test_type' => [
        'ACT',
        'SAT',
        'PSAT'
    ],
    'college_size_option' => [
        [
            'option' => 'Small',
            'value' => '1..2000',
        ],
        [
            'option' => 'Medium',
            'value' => '2000..15000',
        ],
        [
            'option' => 'Large',
            'value' => '15001..',
        ]
    ],
    'type_of_school' => [
        [
            'option' => 'Public',
            'value' => 1,
        ],
        [
            'option' => 'Private Nonprofit',
            'value' => 2,
        ],
        [
            'option' => 'Private For-Profit',
            'value' => 3,
        ]
    ],
    'urbanicity' => [
        [
            'option' => 'City',
            'value' => '11,12,13',
        ],
        [
            'option' => 'Suburban',
            'value' => '21,22,23',
        ],
        [
            'option' => 'Town',
            'value' => '31,32,33',
        ],
        [
            'option' => 'Rural',
            'value' => '41,42,43',
        ]
    ],
    'undergraduate_degree_option' => [
        [
            'option' => 'Certificate',
            'value' => 1,
        ],
        [
            'option' => 'Associate\'s Degree',
            'value' => 2,
        ],
        [
            'option' => 'Bachelor\'s Degree',
            'value' => 3,
        ]
    ],
    'graduate_degree_option' => [
        [
            'option' => 'Master\'s Degree',
            'value' => 5,
        ],
        [
            'option' => 'Post-baccalaureate Certificate',
            'value' => 4,
        ],
        [
            'option' => 'Doctoral Degree',
            'value' => 6,
        ],
        [
            'option' => 'First Professional Degree',
            'value' => 7,
        ],
        [
            'option' => 'Graduate/Professional Certificate',
            'value' => 8,
        ]
    ],
    'specialized_mission_options' => [
        [
            'option' => 'Women-Only',
            'value' => 1,
            'search_key' => 'school.women_only'
        ],
        [
            'option' => 'Men-Only',
            'value' => 1,
            'search_key' => 'school.men_only'
        ],
        [
            'option' => 'Asian American and Native American Pacific Islander-Serving Institution',
            'value' => 1,
            'search_key' => 'school.minority_serving.aanipi'
        ],
        [
            'option' => 'Alaska Native and Native Hawaiian-Serving Institution',
            'value' => 1,
            'search_key' => 'school.minority_serving.annh'
        ],
        [
            'option' => 'Hispanic-Serving Institution',
            'value' => 1,
            'search_key' => 'school.minority_serving.hispanic'
        ],
        [
            'option' => 'Historically Black College and University',
            'value' => 1,
            'search_key' => 'school.minority_serving.historically_black'
        ],
        [
            'option' => 'Native American Non-Tribal Institution',
            'value' => 1,
            'search_key' => 'school.minority_serving.nant'
        ],
        [
            'option' => 'Predominantly Black Institution',
            'value' => 1,
            'search_key' => 'school.minority_serving.predominantly_black'
        ],
        [
            'option' => 'Tribal College and University',
            'value' => 1,
            'search_key' => 'school.minority_serving.tribal'
        ]
    ],
    'religious_affiliation_options' => [
        [
            'option' => 'African Methodist Episcopal',
            'value' => 51,
        ],
        [
            'option' => 'African Methodist Episcopal Zion Church',
            'value' => 24,
        ],
        [
            'option' => 'American Baptist',
            'value' => 52,
        ],
        [
            'option' => 'American Evangelical Lutheran Church',
            'value' => 22,
        ],
        [
            'option' => 'American Lutheran',
            'value' => 53,
        ],
        [
            'option' => 'Assemblies of God Church',
            'value' => 27,
        ],
        [
            'option' => 'Baptist',
            'value' => 54,
        ],
        [
            'option' => 'Brethren Church',
            'value' => 28,
        ],
        [
            'option' => 'Christ and Missionary Alliance Church',
            'value' => 34,
        ],
        [
            'option' => 'Christian Church (Disciples of Christ)',
            'value' => 61,
        ],
        [
            'option' => 'Christian Churches and Churches of Christ',
            'value' => 48,
        ],
        [
            'option' => 'Christian Methodist Episcopal',
            'value' => 55,
        ],
        [
            'option' => 'Christian Reformed Church',
            'value' => 35,
        ],
        [
            'option' => 'Church of Brethren',
            'value' => 58,
        ],
        [
            'option' => 'Church of God',
            'value' => 57,
        ],
        [
            'option' => 'Church of the Nazarene',
            'value' => 59,
        ],
        [
            'option' => 'Churches of Christ',
            'value' => 74,
        ],
        [
            'option' => 'Cumberland Presbyterian',
            'value' => 60,
        ],
        [
            'option' => 'Ecumenical Christian',
            'value' => 101,
        ],
        [
            'option' => 'Episcopal Church, Reformed',
            'value' => 50,
        ],
        [
            'option' => 'Evangelical Christian',
            'value' => 102,
        ],
        [
            'option' => 'Evangelical Congregational Church',
            'value' => 36,
        ],
        [
            'option' => 'Evangelical Covenant Church of America',
            'value' => 37,
        ],
        [
            'option' => 'Evangelical Free Church of America',
            'value' => 38,
        ],
        [
            'option' => 'Evangelical Lutheran Church',
            'value' => 39,
        ],
        [
            'option' => 'Free Methodist',
            'value' => 64,
        ],
        [
            'option' => 'Free Will Baptist Church',
            'value' => 41,
        ],
        [
            'option' => 'Friends',
            'value' => 65,
        ],
        [
            'option' => 'Greek Orthodox',
            'value' => 91,
        ],
        [
            'option' => 'Interdenominational',
            'value' => 42,
        ],
        [
            'option' => 'International United Pentecostal Church',
            'value' => 40,
        ],
        [
            'option' => 'Jewish',
            'value' => 80,
        ],
        [
            'option' => 'Latter Day Saints (Mormon Church)',
            'value' => 94,
        ],
        [
            'option' => 'Lutheran Church - Missouri Synod',
            'value' => 68,
        ],
        [
            'option' => 'Lutheran Church in America',
            'value' => 67,
        ],
        [
            'option' => 'Mennonite Brethren Church',
            'value' => 43,
        ],
        [
            'option' => 'Mennonite Church',
            'value' => 69,
        ],
        [
            'option' => 'Missionary Church Inc',
            'value' => 87,
        ],
        [
            'option' => 'Moravian Church',
            'value' => 44,
        ],
        [
            'option' => 'Multiple Protestant Denomination',
            'value' => 78,
        ],
        [
            'option' => 'North American Baptist',
            'value' => 45,
        ],
        [
            'option' => 'Original Free Will Baptist',
            'value' => 100,
        ],
        [
            'option' => 'Other Protestant',
            'value' => 79,
        ],
        [
            'option' => 'Pentecostal Holiness Church',
            'value' => 47,
        ],
        [
            'option' => 'Presbyterian',
            'value' => 103,
        ],
        [
            'option' => 'Presbyterian Church (USA)',
            'value' => 66,
        ],
        [
            'option' => 'Protestant Episcopal',
            'value' => 73,
        ],
        [
            'option' => 'Protestant, not specified',
            'value' => 77,
        ],
        [
            'option' => 'Reformed Church in America',
            'value' => 49,
        ],
        [
            'option' => 'Reformed Presbyterian Church',
            'value' => 81,
        ],
        [
            'option' => 'Roman Catholic',
            'value' => 30,
        ],
        [
            'option' => 'Russian Orthodox',
            'value' => 92,
        ],
        [
            'option' => 'Seventh Day Adventists',
            'value' => 95,
        ],
        [
            'option' => 'Southern Baptist',
            'value' => 75,
        ],
        [
            'option' => 'The Presbyterian Church in America',
            'value' => 97,
        ],
        [
            'option' => 'Undenominational',
            'value' => 88,
        ],
        [
            'option' => 'Unitarian Universalist',
            'value' => 93,
        ],
        [
            'option' => 'United Brethren Church',
            'value' => 84,
        ],
        [
            'option' => 'United Church of Christ',
            'value' => 76,
        ],
        [
            'option' => 'United Methodist',
            'value' => 71,
        ],
        [
            'option' => 'Wesleyan',
            'value' => 89,
        ],
        [
            'option' => 'Seventh Day Adventists',
            'value' => 33,
        ],
        [
            'option' => 'Wisconsin Evangelical Lutheran Synod',
            'value' => 99,
        ]
    ],
    'SAT_Score_table' => [
        'math' => [
            '0' => 200,
            '1' => 200,
            '2' => 210,
            '3' => 230,
            '4' => 240,
            '5' => 260,
            '6' => 280,
            '7' => 290,
            '8' => 310,
            '9' => 320,
            '10' => 330,
            '11' => 340,
            '12' => 360,
            '13' => 370,
            '14' => 380,
            '15' => 390,
            '16' => 410,
            '17' => 420,
            '18' => 430,
            '19' => 440,
            '20' => 450,
            '21' => 460,
            '22' => 470,
            '23' => 480,
            '24' => 480,
            '25' => 490,
            '26' => 500,
            '27' => 510,
            '28' => 520,
            '29' => 520,
            '30' => 530,
            '31' => 540,
            '32' => 550,
            '33' => 560,
            '34' => 560,
            '35' => 570,
            '36' => 580,
            '37' => 590,
            '38' => 600,
            '39' => 600,
            '40' => 610,
            '41' => 620,
            '42' => 630,
            '43' => 640,
            '44' => 650,
            '45' => 660,
            '46' => 670,
            '47' => 670,
            '48' => 680,
            '49' => 690,
            '50' => 700,
            '51' => 710,
            '52' => 730,
            '53' => 740,
            '54' => 750,
            '55' => 760,
            '56' => 780,
            '57' => 790,
            '58' => 800,
        ],
        'reading' => [
            '0' => 10,
            '1' => 10,
            '2' => 10,
            '3' => 11,
            '4' => 12,
            '5' => 13,
            '6' => 14,
            '7' => 15,
            '8' => 15,
            '9' => 16,
            '10' => 17,
            '11' => 17,
            '12' => 19,
            '13' => 19,
            '14' => 19,
            '15' => 20,
            '16' => 20,
            '17' => 21,
            '18' => 21,
            '19' => 22,
            '20' => 22,
            '21' => 23,
            '22' => 23,
            '23' => 24,
            '24' => 24,
            '25' => 25,
            '26' => 25,
            '27' => 26,
            '28' => 26,
            '29' => 27,
            '30' => 28,
            '31' => 28,
            '32' => 29,
            '33' => 29,
            '34' => 30,
            '35' => 30,
            '36' => 31,
            '37' => 31,
            '38' => 32,
            '39' => 32,
            '40' => 33,
            '41' => 33,
            '42' => 34,
            '43' => 35,
            '44' => 35,
            '45' => 36,
            '46' => 37,
            '47' => 37,
            '48' => 38,
            '49' => 38,
            '50' => 39,
            '51' => 40,
            '52' => 40,
        ],
        'write' => [
            '0' => 10,
            '1' => 10,
            '2' => 10,
            '3' => 10,
            '4' => 11,
            '5' => 12,
            '6' => 13,
            '7' => 13,
            '8' => 14,
            '9' => 15,
            '10' => 16,
            '11' => 16,
            '12' => 17,
            '13' => 18,
            '14' => 19,
            '15' => 19,
            '16' => 20,
            '17' => 21,
            '18' => 21,
            '19' => 22,
            '20' => 23,
            '21' => 23,
            '22' => 24,
            '23' => 25,
            '24' => 25,
            '25' => 26,
            '26' => 26,
            '27' => 27,
            '28' => 28,
            '29' => 28,
            '30' => 29,
            '31' => 30,
            '32' => 30,
            '33' => 31,
            '34' => 32,
            '35' => 32,
            '36' => 33,
            '37' => 34,
            '38' => 34,
            '39' => 35,
            '40' => 36,
            '41' => 37,
            '42' => 38,
            '43' => 39,
            '44' => 40,
        ]
    ],
    'PSAT_Score_table' => [
        'math' => [
            '0' => 160,
            '1' => 190,
            '2' => 210,
            '3' => 240,
            '4' => 270,
            '5' => 290,
            '6' => 320,
            '7' => 340,
            '8' => 360,
            '9' => 370,
            '10' => 390,
            '11' => 400,
            '12' => 420,
            '13' => 430,
            '14' => 440,
            '15' => 460,
            '16' => 470,
            '17' => 480,
            '18' => 490,
            '19' => 500,
            '20' => 510,
            '21' => 520,
            '22' => 530,
            '23' => 540,
            '24' => 550,
            '25' => 560,
            '26' => 570,
            '27' => 580,
            '28' => 580,
            '29' => 590,
            '30' => 600,
            '31' => 610,
            '32' => 620,
            '33' => 630,
            '34' => 640,
            '35' => 650,
            '36' => 670,
            '37' => 680,
            '38' => 690,
            '39' => 710,
            '40' => 720,
            '41' => 730,
            '42' => 730,
            '43' => 740,
            '44' => 740,
            '45' => 750,
            '46' => 750,
            '47' => 760,
            '48' => 760,
        ],
        'reading' => [
            '0' => 8,
            '1' => 9,
            '2' => 10,
            '3' => 11,
            '4' => 12,
            '5' => 14,
            '6' => 15,
            '7' => 16,
            '8' => 16,
            '9' => 17,
            '10' => 18,
            '11' => 18,
            '12' => 19,
            '13' => 19,
            '14' => 20,
            '15' => 20,
            '16' => 21,
            '17' => 21,
            '18' => 22,
            '19' => 22,
            '20' => 23,
            '21' => 23,
            '22' => 24,
            '23' => 24,
            '24' => 25,
            '25' => 26,
            '26' => 26,
            '27' => 27,
            '28' => 27,
            '29' => 28,
            '30' => 28,
            '31' => 29,
            '32' => 29,
            '33' => 30,
            '34' => 30,
            '35' => 31,
            '36' => 31,
            '37' => 32,
            '38' => 32,
            '39' => 33,
            '40' => 34,
            '41' => 34,
            '42' => 35,
            '43' => 36,
            '44' => 37,
            '45' => 37,
            '46' => 38,
            '47' => 38,
        ],
        'write' => [
            '0' => 8,
            '1' => 9,
            '2' => 10,
            '3' => 11,
            '4' => 12,
            '5' => 13,
            '6' => 14,
            '7' => 14,
            '8' => 15,
            '9' => 15,
            '10' => 16,
            '11' => 16,
            '12' => 17,
            '13' => 18,
            '14' => 18,
            '15' => 19,
            '16' => 20,
            '17' => 20,
            '18' => 21,
            '19' => 21,
            '20' => 22,
            '21' => 23,
            '22' => 24,
            '23' => 24,
            '24' => 25,
            '25' => 25,
            '26' => 26,
            '27' => 27,
            '28' => 27,
            '29' => 28,
            '30' => 28,
            '31' => 29,
            '32' => 29,
            '33' => 30,
            '34' => 30,
            '35' => 31,
            '36' => 32,
            '37' => 32,
            '38' => 33,
            '39' => 34,
            '40' => 35,
            '41' => 36,
            '42' => 37,
            '43' => 37,
            '44' => 38,
        ]
    ],
    'entrance_difficulty' => [
        'Not Reported',
        'Noncompetitive',
        'Moderately Difficult',
        'Most Difficult'
    ],
    'college_list_per_page' => 20,
    'deadline_notification_frequency' => [
        'day',
        'week',
        'month'
    ],
    'reminder_brefore_frequncy' => [
        'hour',
        'day',
        'week',
        'month'
    ]
]
?>