<?php

return [
    'states' => [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "District Of Columbia",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming"
    ],

    'graduation_designation' => [
        "STEM Scholar",
        "IB Diploma Candidate",
        "Business Certification",
        "Conservatory Arts Certification",
        "Summa Cum Laude",
        "Magna Cum Laude",
        "Cum Laude",
        "Valedictorian",
        "Salutatorian",
        "Fillable"
    ],

    'cities' => [
        "New York",
        "Los Angeles",
        "Chicago",
        "Houston"
    ],

    'ib_courses' => [
        "Business Management",
        "Chemistry",
        "Classical Languages",
        "Computer Science",
        "Dance",
        "Design Technology",
        "Economics",
        "Environmental Systems and Societies",
        "Film",
        "Geography",
        "Global Politics",
        "Information Technology in a Global Society",
        "Language A: Literature",
        "Language A: Language and Literature",
        "Language ab Initio",
        "Language B",
        "Literature and Performance",
        "Mathematics: Analysis and Approaches",
        "Mathematics: Applications and Interpretations",
        "Music",
        "Philosophy",
        "Psychology",
        "Physics",
        "Social and Cultural Anthropology",
        "Sports, Exercise, and Health Science",
        "Theatre",
        "Theory of Knowledge",
        "Visual Art",
        "World Religion"
    ],

    'ap_courses' => [
        "Art and Design - 2-D Design",
        "Art and Design - 3-D Design",
        "Art and Design - Drawing",
        "Art History",
        "Biology",
        "Calculus AB",
        "Calculus BC",
        "Chemistry",
        "Chinese Language and Culture",
        "Computer Science A",
        "Computer Science Principles",
        "English Language and Composition",
        "English Literature and Composition",
        "Environmental Science",
        "European History",
        "French Language and Culture",
        "German Language and Culture",
        "Government and Politics (Comparative)",
        "Government and Politics (US)",
        "Human Geography",
        "Italian Language and Culture",
        "Japanese Language and Culture",
        "Latin",
        "Macroeconomics",
        "Microeconomics",
        "Music Theory",
        "Physics 1: Algebra-Based",
        "Physics 2: Algebra-Based",
        "Physics C: Electricity and Magnetism",
        "Physics C: Mechanics",
        "Psychology",
        "Research",
        "Seminar",
        "Spanish Language and Culture",
        "Spanish Literature and Culture",
        "Statistics",
        "US History",
        "World History: Modern"
    ],

    'honors_courses_name' => [
        "Algebra I",
        "Algebra II",
        "Biology",
        "Chemistry",
        "Economics",
        "English 9",
        "English10",
        "English 11",
        "English 12",
        "Geometry",
        "Physics",
        "Physical Science",
        "Pre-Calculus",
        "U.S. History",
        "U.S. Geography",
        "World Geography",
        "World History",
        "American Sign Language",
        "Ancient Greek",
        "Arabic",
        "Chinese",
        "French",
        "German",
        "Hebrew",
        "Italian",
        "Japanese",
        "Korean",
        "Latin",
        "Portuguese",
        "Russian",
        "Spanish",
    ],

    "demonstrated_positions" => [
        "Assistant",
        "Attendee",
        "Barista",
        "Busser",
        "Chair",
        "Captain",
        "Chef",
        "Co-Captain",
        "Co-Leader",
        "Co-Founder",
        "Conducted Career Interview",
        "Created",
        "Customer Service",
        "Employee",
        "Developer",
        "Director",
        "Front of House Team Member",
        "Founder",
        "Intern",
        "Internship",
        "Initiated",
        "Job Shadow",
        "JV Starter",
        "JV Member",
        "Lead",
        "Leader",
        "Manager",
        "Member",
        "Observed",
        "Officer",
        "Operated",
        "Organizer",
        "Owner",
        "Owner & Founder",
        "Participant",
        "President",
        "Recorder",
        "Reporter",
        "Representative",
        "Researcher",
        "Scout",
        "Secretary",
        "Self-Employed",
        "Shift Lead",
        "Shift Manager",
        "Starter",
        "State Officer",
        "State Representative",
        "Summer Student",
        "Student",
        "Vice President",
        "Team Manager",
        "Treasurer",
        "Varsity Starter",
        "Varsity Member",
        "Volunteer",
        "Worker",
        "Fillable"
    ]


];


   

?>