<?php
return array(
  array('id' => '1','state_code' => 'AL','state_name' => 'Alabama'),
  array('id' => '2','state_code' => 'AK','state_name' => 'Alaska'),
  array('id' => '3','state_code' => 'AZ','state_name' => 'Arizona'),
  array('id' => '4','state_code' => 'AR','state_name' => 'Arkansas'),
  array('id' => '5','state_code' => 'CA','state_name' => 'California'),
  array('id' => '6','state_code' => 'CO','state_name' => 'Colorado'),
  array('id' => '7','state_code' => 'CT','state_name' => 'Connecticut'),
  array('id' => '8','state_code' => 'DE','state_name' => 'Delaware'),
  array('id' => '9','state_code' => 'DC','state_name' => 'District of Columbia'),
  array('id' => '10','state_code' => 'FL','state_name' => 'Florida'),
  array('id' => '11','state_code' => 'GA','state_name' => 'Georgia'),
  array('id' => '12','state_code' => 'HI','state_name' => 'Hawaii'),
  array('id' => '13','state_code' => 'ID','state_name' => 'Idaho'),
  array('id' => '14','state_code' => 'IL','state_name' => 'Illinois'),
  array('id' => '15','state_code' => 'IN','state_name' => 'Indiana'),
  array('id' => '16','state_code' => 'IA','state_name' => 'Iowa'),
  array('id' => '17','state_code' => 'KS','state_name' => 'Kansas'),
  array('id' => '18','state_code' => 'KY','state_name' => 'Kentucky'),
  array('id' => '19','state_code' => 'LA','state_name' => 'Louisiana'),
  array('id' => '20','state_code' => 'ME','state_name' => 'Maine'),
  array('id' => '21','state_code' => 'MD','state_name' => 'Maryland'),
  array('id' => '22','state_code' => 'MA','state_name' => 'Massachusetts'),
  array('id' => '23','state_code' => 'MI','state_name' => 'Michigan'),
  array('id' => '24','state_code' => 'MN','state_name' => 'Minnesota'),
  array('id' => '25','state_code' => 'MS','state_name' => 'Mississippi'),
  array('id' => '26','state_code' => 'MO','state_name' => 'Missouri'),
  array('id' => '27','state_code' => 'MT','state_name' => 'Montana'),
  array('id' => '28','state_code' => 'NE','state_name' => 'Nebraska'),
  array('id' => '29','state_code' => 'NV','state_name' => 'Nevada'),
  array('id' => '30','state_code' => 'NH','state_name' => 'New Hampshire'),
  array('id' => '31','state_code' => 'NJ','state_name' => 'New Jersey'),
  array('id' => '32','state_code' => 'NM','state_name' => 'New Mexico'),
  array('id' => '33','state_code' => 'NY','state_name' => 'New York'),
  array('id' => '34','state_code' => 'NC','state_name' => 'North Carolina'),
  array('id' => '35','state_code' => 'ND','state_name' => 'North Dakota'),
  array('id' => '36','state_code' => 'OH','state_name' => 'Ohio'),
  array('id' => '37','state_code' => 'OK','state_name' => 'Oklahoma'),
  array('id' => '38','state_code' => 'OR','state_name' => 'Oregon'),
  array('id' => '39','state_code' => 'PA','state_name' => 'Pennsylvania'),
  array('id' => '40','state_code' => 'PR','state_name' => 'Puerto Rico'),
  array('id' => '41','state_code' => 'RI','state_name' => 'Rhode Island'),
  array('id' => '42','state_code' => 'SC','state_name' => 'South Carolina'),
  array('id' => '43','state_code' => 'SD','state_name' => 'South Dakota'),
  array('id' => '44','state_code' => 'TN','state_name' => 'Tennessee'),
  array('id' => '45','state_code' => 'TX','state_name' => 'Texas'),
  array('id' => '46','state_code' => 'UT','state_name' => 'Utah'),
  array('id' => '47','state_code' => 'VT','state_name' => 'Vermont'),
  array('id' => '48','state_code' => 'VA','state_name' => 'Virginia'),
  array('id' => '49','state_code' => 'WA','state_name' => 'Washington'),
  array('id' => '50','state_code' => 'WV','state_name' => 'West Virginia'),
  array('id' => '51','state_code' => 'WI','state_name' => 'Wisconsin'),
  array('id' => '52','state_code' => 'WY','state_name' => 'Wyoming')
);
